let BtnDecide = document.getElementById("BtnDecide");
const PDecision = document.getElementById("PDecision");
const form = document.getElementById("form");
const imagemGif = document.getElementById("ImagemGif");

const gifsTalvez = ["https://media1.giphy.com/media/Tg6Gp5NSP45bsat4sf/giphy.webp",
    "https://media1.giphy.com/media/jqNn2Dn078gzsCem8g/giphy.gif?cid=ecf05e47ffbbf500e915ca70646736b651919c050f412147&rid=giphy.gif",
    "https://media3.giphy.com/media/xUNemVaUZFSgHxvQXK/giphy.gif?cid=ecf05e47ffbbf500e915ca70646736b651919c050f412147&rid=giphy.gif",
    "https://media2.giphy.com/media/xTkcEzYtwmQl3UNUlO/200.webp?cid=790b7611bd0fb063e60768c47386a34658f641745cd399cd&rid=200.webp",
    "https://media0.giphy.com/media/3oKIPjHdsUZOlJXTQQ/200.webp?cid=790b7611bd0fb063e60768c47386a34658f641745cd399cd&rid=200.webp",
    "https://media.giphy.com/media/xUOrw1XgmZUiVpGTDi/giphy.gif",
    "https://media.giphy.com/media/euwGSQV9J0qmaiucL8/giphy.gif",
    "https://media.giphy.com/media/3o7TKHKjrDyqphX9Cg/giphy.gif",
    "https://media.giphy.com/media/XeGUOwWa6eV8Q0tR3o/giphy.gif",
    "https://media.giphy.com/media/uH7MRQvoBXWg0/giphy.gif",
    "https://media.giphy.com/media/WUOGZeXzNZBN6/giphy.gif",
    "https://media.giphy.com/media/ZufDoXTkvu9Wg/giphy.gif",
    "https://media.giphy.com/media/3ohhwfJn1pdcXIJy48/giphy.gif",
    "https://media.giphy.com/media/KVFXdQvD6r2mY/giphy.gif",
    "https://media.giphy.com/media/3oxHQG3DcmkbYYob2o/giphy.gif",
    "https://media.giphy.com/media/ie76dJeem4xBDcf83e/giphy.gif",
    "https://media.giphy.com/media/2siArFxEXIEPrbQvpS/giphy.gif",
    "https://media.giphy.com/media/Mc7glzjN2Ukj4KGvCU/giphy.gif",
    "https://media.giphy.com/media/U5UbACyqOiuUyyhKtu/giphy.gif",
    "https://media.giphy.com/media/UQJ5yo5d6dNARSvO8I/giphy.gif",
    "https://media.giphy.com/media/Y4nLVEXzl9lhayadHH/giphy.gif",
    "https://media.giphy.com/media/uB08QkttrJ2vdIlRid/giphy.gif",
    "https://media.giphy.com/media/Ri20jXd9WDXIiXRpgL/giphy.gif",
    "https://media.giphy.com/media/6TNRjxSXMjMC4/giphy.gif",
    "https://media.giphy.com/media/TJ7hXERD1NmrS/giphy.gif",
    "https://media.giphy.com/media/mAp06hYS4WnPq/giphy.gif",
    "https://media.giphy.com/media/5i0dN8aOoBE3e/giphy.gif",
    "https://media.giphy.com/media/VRDYNcaU0nUhW/giphy.gif",
    "https://media.giphy.com/media/YXv5N7nY7rkCA/giphy.gif",
    "https://media.giphy.com/media/Z9tvqoD1SEQcomTVaK/giphy.gif",
    "https://media2.giphy.com/media/cLcxtL1z8t8oo/giphy.webp?cid=790b7611b3e2c6bcc7be9ed68c3a728159ebf531194cc705&rid=giphy.webp",
    "https://media.giphy.com/media/fItgT774J3nWw/giphy.gif",
    "https://media.giphy.com/media/3ohzdYGKrPn8GzgAes/giphy.gif",
    "https://media.giphy.com/media/9DctaOQnk7GX0LIxj9/giphy.gif",
    "https://media.giphy.com/media/UuebWyG4pts3rboawU/giphy.gif",
    "https://media.giphy.com/media/TFxnSHo3UGesnHGMI0/giphy.gif",
    "https://media.giphy.com/media/3ohc13lGnOGpMHn7zO/giphy.gif",
    "https://media.giphy.com/media/ZNegC7wFpuQT7nurZ0/giphy.gif",
    "https://media.giphy.com/media/moyzrwjUIkdNe/giphy.gif",
    "https://media.giphy.com/media/KEh5kliRTSVJm/giphy.gif",
    "https://media.giphy.com/media/B2vBunhgt9Pc4/giphy.gif",
    "https://media.giphy.com/media/LT7KeAUzVGgD7JKvSD/giphy.gif",
    "https://media.giphy.com/media/1MayKbFuSKE1O/giphy.gif",
    "https://media.giphy.com/media/9JgfPxZ5pofIVjFleH/giphy.gif",
    "https://media.giphy.com/media/Ov5NiLVXT8JEc/giphy.gif",
    "https://media.giphy.com/media/13borq7Zo2kulO/giphy.gif",
    "https://media.giphy.com/media/jS6sVMK2fu4Uw/giphy.gif",
    "https://media.giphy.com/media/11c7UUfN4eoHF6/giphy.gif",
    "https://media.giphy.com/media/3o72EX5QZ9N9d51dqo/giphy.gif",
    "https://media.giphy.com/media/OmK8lulOMQ9XO/giphy.gif",
    "https://media.giphy.com/media/UotLuplZSzKRa/giphy.gif",
    "https://media.giphy.com/media/dIVa0pwco4Mj5rQ7gy/giphy.gif",
    "https://media.giphy.com/media/1ViLp0GBYhTcA/giphy.gif",
    "https://media.giphy.com/media/H4DjXQXamtTiIuCcRU/giphy.gif",
    "https://media.giphy.com/media/JfLdIahamXQI0/giphy.gif",
    "https://media.giphy.com/media/ND6xkVPaj8tHO/giphy.gif",
    "https://media.giphy.com/media/a5viI92PAF89q/giphy.gif",
    "https://media.giphy.com/media/xTiTnlWmMuH2tlu5BS/giphy.gif",
    "https://media.giphy.com/media/wDgw1fJF8hzMY/giphy.gif",
    "https://media.giphy.com/media/7CvzHW7inDNew/giphy.gif",
    "https://media.giphy.com/media/xTiTnwLP3dudqPVams/giphy.gif",
    "https://media.giphy.com/media/l41lLsIkfHpJlhR9m/giphy.gif",
    "https://media.giphy.com/media/dRazPhaLHNIFq/giphy.gif",
    "https://media.giphy.com/media/Pmc0PM7tdCp7G/giphy.gif",
    "https://media.giphy.com/media/SjRgoSG1RTpYs/giphy.gif",
    "https://media.giphy.com/media/yoJC2lBC8bIUKsM75K/giphy.gif",
    "https://media.giphy.com/media/NyTBnC5xvENig/giphy.gif",
    "https://media.giphy.com/media/IR3zZCWXz5DGg/giphy.gif",
    "https://media.giphy.com/media/845KbjkK4g9yw/giphy.gif",
    "https://media.giphy.com/media/NPAB0vUr8nfR6/giphy.gif",
    "https://media.giphy.com/media/WKkCdjq3A0weY/giphy.gif",
    "https://media.giphy.com/media/9EPyg0QS1zc6A/giphy.gif",
    "https://media.giphy.com/media/10KJjcguH0t7ji/giphy.gif",
    "https://media.giphy.com/media/QwZ4DVuJpkJZS/giphy.gif",
    "https://media.giphy.com/media/d9wv4feTktObm/giphy.gif",
    "https://media.giphy.com/media/mJzayaTmOLKaQ/giphy.gif",
    "https://media.giphy.com/media/KOS39Lrl3c4iA/giphy.gif",
    "https://media.giphy.com/media/XH1X6zGZKSYXS/giphy.gif",
    "https://media.giphy.com/media/uRcoPXfNZUMp2/giphy.gif",
    "https://media.giphy.com/media/3o85xnYxeojLcZ7GNy/giphy.gif",
    "https://media.giphy.com/media/3o85xzAtzzj3wvmBAQ/giphy.gif",
    "https://media.giphy.com/media/KV7lcpQOlJ3fG/giphy.gif",
    "https://media.giphy.com/media/3o85xLgLTQmbJC6z8Q/giphy.gif",
    "https://media.giphy.com/media/EbLhhaLigrEIg/giphy.gif",
    "https://media.giphy.com/media/eb7C5lHhOd8t2/giphy.gif",
    "https://media.giphy.com/media/O1Jta0SBVuYDu/giphy.gif",
    "https://media.giphy.com/media/l0O9zrbtv8ALhvqi4/giphy.gif",
    "https://media.giphy.com/media/DvrEgDNAAnb0c/giphy.gif",
    "https://media.giphy.com/media/3xz2BPaejjldad6bMk/giphy.gif",
    "https://media.giphy.com/media/5yLgocExKLnK8U6RDMc/giphy.gif",
    "https://media.giphy.com/media/13mJuE1L3WUzny/giphy.gif",
    "https://media.giphy.com/media/dC79F4lsUyJ4A/giphy.gif",
    "https://media.giphy.com/media/7u6iYSWfi0ybe/giphy.gif",
    "https://media.giphy.com/media/AxVvjIqj8aWBzF85jy/giphy.gif",
    "https://media.giphy.com/media/zraj11LOUptNsNDfTv/giphy.gif",
    "https://media.giphy.com/media/UuAxmTtt0JNHq/giphy.gif",
    "https://media.giphy.com/media/iF0J8RlEJamCQ/giphy.gif",
    "https://media.giphy.com/media/E2W7fUKLbhwUE/giphy.gif",
    "https://media.giphy.com/media/FfPPGZCwaAARq/giphy.gif",
    "https://media.giphy.com/media/YX9vAQVjdIIx2/giphy.gif",
    "https://media.giphy.com/media/VS0xcCPGhqjoA/giphy.gif",
    "https://media.giphy.com/media/M8CXF5bVLGrbG/giphy.gif",
    "https://media.giphy.com/media/5yLgocm86JXFSU8pgFq/giphy.gif",
    "https://media.giphy.com/media/k1a1k2vkcMJZ6/giphy.gif",
    "https://media.giphy.com/media/fDHd5iAlDwKuQ/giphy.gif",
    "https://media.giphy.com/media/lOVOJ7BWb7YWc/giphy.gif",
    "https://media.giphy.com/media/M1ZRSbTyYHlCg/giphy.gif",
    "https://media.giphy.com/media/HDqKexJ88OTmw/giphy.gif",
    "https://media.giphy.com/media/2Fj37NvozJWNO/giphy.gif",
    "https://media.giphy.com/media/pDfBRjK4rofm/giphy.gif",
    "https://media.giphy.com/media/AAxO4lYisy4co/giphy.gif",
    "https://media.giphy.com/media/mPW9NepGQn0uQ/giphy.gif",
    "https://media.giphy.com/media/orVa44Oav5WoF1LVOE/giphy.gif",
    "https://media.giphy.com/media/EWfclmljEinV6/giphy.gif",
    "https://media.giphy.com/media/tIRUa2cyXmHU4/giphy.gif",
    "https://media.giphy.com/media/3rgXBHavLDn9WPNheM/giphy.gif",
    "https://media.giphy.com/media/QlN9yjP1epryw/giphy.gif",
    "https://media.giphy.com/media/xTiTny2yBG5vGDS0SI/giphy.gif",
    "https://media.giphy.com/media/l41lFYeLmNE4DZP6U/giphy.gif",
    "https://media.giphy.com/media/GFcf9SDZERJq8/giphy.gif",
    "https://media.giphy.com/media/YILp9aWLMpqnK/giphy.gif",
    "https://media.giphy.com/media/pGg5T6k9pWiFG/giphy.gif",
    "https://media.giphy.com/media/abdf0NKI55852/giphy.gif",
    "https://media.giphy.com/media/bnWHpx31jJATS/giphy.gif",
    "https://media.giphy.com/media/dEhpOcdoOJtDy/giphy.gif",
    "https://media.giphy.com/media/xTiTnBzmxbZlMPdhlu/giphy.gif",
    "https://media.giphy.com/media/xTiTnm0WLznM5aboTC/giphy.gif",
    "https://media.giphy.com/media/yoJC2ORv97vYg5PNVS/giphy.gif",
    "https://media.giphy.com/media/3rgXBCw8sMGsinikkU/giphy.gif",
    "https://media.giphy.com/media/10IrVF7KGmvM0o/giphy.gif",
    "https://media.giphy.com/media/6fScAIQR0P0xW/giphy.gif",
    "https://media.giphy.com/media/4SNQVF2WYOGe4/giphy.gif"

]
const gifsYap = ["https://media.giphy.com/media/66Z5s4rg6bNHa/giphy.gif",
    "https://media.giphy.com/media/3gXLvh7Vszm3OvYTh8/giphy.gif",
    "https://media.giphy.com/media/4UJyRK2TXNhgk/giphy.gif",
    "https://media.giphy.com/media/xULW8A2apYzG3R95y8/giphy.gif",
    "https://media.giphy.com/media/l3vRh0dN9Hg66q5HO/giphy.gif",
    "https://media.giphy.com/media/BsrdT9jZA03te/giphy.gif",
    "https://media.giphy.com/media/nXxOjZrbnbRxS/giphy.gif",
    "https://media.giphy.com/media/DffShiJ47fPqM/giphy.gif",
    "https://media.giphy.com/media/S3Ot3hZ5bcy8o/giphy.gif",
    "https://media.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif",
    "https://media.giphy.com/media/pNpONEEg3pLIQ/giphy.gif",
    "https://media.giphy.com/media/JE6xHkcUPtYs0/giphy.gif",
    "https://media.giphy.com/media/efJ3wU9Z8SLdUnpUem/giphy.gif",
    "https://media.giphy.com/media/J336VCs1JC42zGRhjH/giphy.gif",
    "https://media.giphy.com/media/1tHzw9PZCB3gY/giphy.gif",
    "https://media.giphy.com/media/oGO1MPNUVbbk4/giphy.gif",
    "https://media.giphy.com/media/3o7TKo6fiRVhQlgoPS/giphy.gif",
    "https://media.giphy.com/media/yFs12GkGa4Cpq/giphy.gif",
    "https://media.giphy.com/media/xT1XGzgkBT1IdfMbDi/giphy.gif",
    "https://media.giphy.com/media/kwCLw42hH2cxvIywIi/giphy.gif",
    "https://media.giphy.com/media/3o6Zt7mutmbv76m0ko/giphy.gif",
    "https://media.giphy.com/media/xUA7baWfTjfHGLZc3e/giphy.gif"
];
const gifsNop = ["https://media.giphy.com/media/2WGYAQZ52I6wQecREk/giphy.gif",
    "https://media.giphy.com/media/JlmTHZYckDZJu/giphy.gif",
    "https://media.giphy.com/media/LRKET0Syb0rDO/giphy.gif",
    "https://media.giphy.com/media/3o6ZsZKbgw4QVWEbzq/giphy.gif",
    "https://media.giphy.com/media/ftqLysT45BJMagKFuk/giphy.gif",
    "https://media.giphy.com/media/T5QOxf0IRjzYQ/giphy.gif",
    "https://media.giphy.com/media/iGAn18RZYjk7R8l0Oh/giphy.gif",
    "https://media.giphy.com/media/fsPcMdeXPxSP6zKxCA/giphy.gif",
    "https://media.giphy.com/media/54Y38YdCPe58XA0FpJ/giphy.gif",
    "https://media.giphy.com/media/l49JJQf9w3RPCWDyU/giphy.gif",
    "https://media.giphy.com/media/26BoEBp33RFNV77Ne/giphy.gif",
    "https://media.giphy.com/media/l2SqgrtL7pjAOizSg/giphy.gif",
    "https://media.giphy.com/media/3o7bu6Qs4WE8ZRinDi/giphy.gif"
];

form.addEventListener(
    "submit",
    event => {
        event.preventDefault();
        const num1 = Math.floor((Math.random() * 3) + 1);

        BtnDecide.disabled = true;
        PDecision.textContent = "A Ler A Pergunta";
        imagemGif.src = "../../Imagens/Outros/Ball_2D_Animation.gif";


        setTimeout(function() {

            if (num1 === 1) {
                PDecision.textContent = "Yap";
                imagemGif.src = gifsYap[Math.floor((Math.random() * gifsYap.length))];
            } else if (num1 === 2) {
                PDecision.textContent = "Nop";
                imagemGif.src = gifsNop[Math.floor((Math.random() * gifsNop.length))];
            } else {
                PDecision.textContent = "Não Achei Que Mereces Resposta";
                imagemGif.src = gifsTalvez[Math.floor((Math.random() * gifsTalvez.length))];
            }
        }, 1500);

        BtnDecide.disabled = false;
    },
    false,
);