export const history = {
  en: {
    _2016: [
      "Start in Curso Proficional Informática de Gestão;",
      "Frits contac with programing;",
      "Start Algorithm / Pseudocode and Flowcharts;",
      "Learn Pascal basics;",
    ],
    _2017: [
      "Learn Lazarus Pascal basics;",
      "Start learn Visual Basic 2010 basics;",
      "Learn Scratch 2.0;",
      "Learn HTML basics;",
      "Learn ACCESS basics;",
    ],
    _2018: [
      "Keep learn Visual Basic 2010;",
      "Learn Visual Basic 2010 connection to Access DB;",
      "Start learn MIT App Inventor 2 basics;",
      "First professional internship, ULSM;",
      "Learn Java basics;",
    ],
    _2019: [
      "Finish Curso Proficional Informática de Gestão;",
      "Second professional internship, PC Recover (fix computers);",
      "Start Mindera School;",
      "Remember Java basics and intermediate;",
      "Start learn MySQL;",
      "Remember HTML basics and advanced;",
      "Start learn CSS;",
      "Start learn Vanilla JavaScript;",
    ],
    _2020: [
      "Keep learn HTML;",
      "Keep learn CSS;",
      "Keep learn Vanilla JavaScript;",
      "Start learn ReactJS, React-Redux;",
      "Start learn LESS/SASS;",
      "Start learn Bootstrap;",
      "Start learn PHP basics and connection with DB;",
      "Enter on Mindera like a worker;",
    ],
  },
  pt: {
    _2016: [
      "Inicio no Curso Proficional Informática de Gestão;",
      "Primeiro contacto com o mundo da programação;",
      "Inicio a algoritmia / pseudocódigo e fluxogramas;",
      "Aprendi Pascal básico;",
    ],
    _2017: [
      "Aprendi o básico de Lazarus Pascal;",
      "Comecei a aprender os conceitos básicos do Visual Basic 2010;",
      "Aprendi Scratch 2.0;",
      "Aprendi HTML básico;",
      "Aprendi os básicos de ACCESS;",
    ],
    _2018: [
      "Continuação deVisual Basic 2010;",
      "Aprendi a conectar o Visual Basic 2010 com o ACCESS;",
      "Inicio dos basicos de MIT App Inventor 2;",
      "Primeiro estágio profissional, ULSM;",
      "Aprendi o Java básico;",
    ],
    _2019: [
      "Concluir Curso Profissional de Informática de Gestão;",
      "Segundo estágio profissional, PC Recover (consertar computadores);",
      "Entrei na Mindera School;",
      "Relembrar do básico de Java e intermediário;",
      "Comecei a aprender MySQL;",
      "Relembrar dos conceitos básicos e HTML avançado;",
      "Comece a aprender CSS/VanillaJS;",
    ],
    _2020: [
      "Continuei a aprender HTML/CSS/VanillaJS;",
      "Comecei a aprender ReactJS, React-Redux;",
      "Comecei a aprender LESS / SASS;",
      "Comecei a aprender Bootstrap;",
      "Comecei a aprender o básico do PHP e conexão com Base de Dados;",
      "Entrei na Mindera como um trabalhador;",
    ],
  },
};
