name: Github Pages Deploy

on:
  push:
    branches:
      - master
      - "V2-Phaser-Game"
  pull_request:
    branches:
      - master
      - "V2-Phaser-Game"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ------- V2-Phaser-Game --------
      - name: Checkout the `V2-Phaser-Game` branch
        uses: actions/checkout@v2
        with:
          ref: V2-Phaser-Game
          clean: false

      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm ci

      - name: Build # Output build files in `dist` folder
        run: npm run build

      # ------- gh-pages (deploy) --------
      - name: Deploy in gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
